CREATE DATABASE BDPrueba
GO

USE BDPrueba
GO
 -- Creacion de tablas
CREATE TABLE MUNICIPIO(
CODIGO_MUNICIPIO INT PRIMARY KEY NOT NULL,
NOMBRE_MUNICIPIO VARCHAR(50) NOT NULL,
ESTADO BIT NOT NULL,
)
GO

CREATE TABLE REGION(
CODIGO_REGION INT IDENTITY PRIMARY KEY NOT NULL,
NOMBRE_REGION VARCHAR(50) NOT NULL,
)
GO

CREATE TABLE MUNICIPIO_REGION(
CODIGO_MUNICIPIO INT NOT NULL,
CODIGO_REGION INT NOT NULL,

CONSTRAINT Fk_Municipio_Region_Municipio
FOREIGN KEY(CODIGO_MUNICIPIO) REFERENCES MUNICIPIO(CODIGO_MUNICIPIO)
   ON UPDATE CASCADE
   ON DELETE CASCADE,
CONSTRAINT Fk_Municipio_Region_Region
FOREIGN KEY(CODIGO_REGION) REFERENCES REGION(CODIGO_REGION)
   ON UPDATE CASCADE
   ON DELETE CASCADE
)
GO

--Insertar datos de prueba

INSERT INTO MUNICIPIO VALUES(214,'Medellin', 1),(466,'Bello', 1),(567,'Itagui', 1),(685,'Estrella', 1)
INSERT INTO REGION VALUES('Andina'),('Amazonia'),('Caribe'),('Pacifico')
INSERT INTO MUNICIPIO_REGION VALUES(214,3),(466,2),(567,2),(214,4),(685,3),(567,3),(685,4)

---Creacion de procedimientos almacenados

CREATE PROCEDURE USP_INSERTARMUNICIPIO
@codigo INT,
@nombre VARCHAR(50),
@estado BIT,
@region INT
AS
BEGIN
    
	 INSERT INTO MUNICIPIO VALUES(@codigo, @nombre, @estado);
     INSERT INTO MUNICIPIO_REGION VALUES(@codigo, @region);
END
-- USP_INSERTARMUNICIPIO 
GO

CREATE PROCEDURE USP_INSERTAREGION
@nombre VARCHAR(50),
@municipio INT
AS
BEGIN

   DECLARE @codigo int;
   INSERT INTO REGION VALUES(@nombre);
   SET @codigo = (SELECT MAX(CODIGO_REGION) FROM REGION)
   INSERT INTO MUNICIPIO_REGION VALUES(@municipio, @codigo);
END
-- exec USP_INSERTAREGION
GO

CREATE PROCEDURE USP_LISTARREGION
AS
BEGIN
  SELECT CODIGO_REGION, NOMBRE_REGION FROM REGION
END
-- USP_LISTARREGION 
GO

CREATE PROCEDURE USP_LISTARMUNICIPIO
AS
BEGIN
  SELECT CODIGO_MUNICIPIO, NOMBRE_MUNICIPIO FROM MUNICIPIO
END
-- USP_LISTARMUNICIPIO 
GO

CREATE PROCEDURE USP_EDITARMUNICIPIO
@codigo int,
@nombre varchar(50),
@estado bit,
@codigoR int
AS
BEGIN
  ---Si el estado es false entonces hay que quitar la asociacion
  
 IF CONVERT(bit, @estado) = 0
 BEGIN
	  DELETE FROM MUNICIPIO_REGION WHERE CODIGO_MUNICIPIO = @codigo and CODIGO_REGION = @codigoR
	  UPDATE MUNICIPIO SET NOMBRE_MUNICIPIO = @nombre, ESTADO = @estado WHERE CODIGO_MUNICIPIO = @codigo
  END	
  ELSE 
  BEGIN
	  UPDATE MUNICIPIO SET NOMBRE_MUNICIPIO = @nombre, ESTADO = @estado WHERE CODIGO_MUNICIPIO = @codigo
	  UPDATE MUNICIPIO_REGION SET CODIGO_REGION = @codigoR WHERE CODIGO_MUNICIPIO = @codigo
  END
END
-- exec USP_EDITARMUNICIPIO 685,'Medellin',1,2
GO

CREATE PROCEDURE USP_EDITARREGION
@codigo int,
@nombre varchar(50),
@codigoM int
AS
BEGIN
  UPDATE REGION SET NOMBRE_REGION = @nombre WHERE CODIGO_REGION = @codigo
  UPDATE MUNICIPIO_REGION SET CODIGO_MUNICIPIO = @codigoM WHERE CODIGO_REGION = @codigo
END
-- exec USP_EDITARREGION 2,'Andina',753
GO


CREATE PROCEDURE USP_ELIMINARREGION
@codigo_r int,
@codigo_m int
AS
BEGIN
  DELETE FROM MUNICIPIO_REGION WHERE CODIGO_REGION = @codigo_r AND CODIGO_MUNICIPIO = @codigo_m
  DELETE FROM REGION WHERE CODIGO_REGION = @codigo_r
END
-- USP_ELIMINARREGION 
GO

CREATE PROCEDURE USP_ELIMINARMUNICIPIO
@codigo_r int,
@codigo_m int
AS
BEGIN
  DELETE FROM MUNICIPIO_REGION WHERE CODIGO_REGION = @codigo_r AND CODIGO_MUNICIPIO = @codigo_m
  --DELETE FROM MUNICIPIO WHERE CODIGO_MUNICIPIO = @codigo_m
END
-- USP_ELIMINARMUNICIPIO 
GO

CREATE PROCEDURE USP_LISTAR_REGION
AS
BEGIN
  SELECT r.CODIGO_REGION AS REGION, r.NOMBRE_REGION, m.CODIGO_MUNICIPIO AS MUNICIPIO, m.NOMBRE_MUNICIPIO FROM REGION r INNER JOIN MUNICIPIO_REGION mr ON r.CODIGO_REGION = mr.CODIGO_REGION INNER JOIN MUNICIPIO m ON m.CODIGO_MUNICIPIO = mr.CODIGO_MUNICIPIO
END
-- USP_LISTAR_REGION 
GO

CREATE PROCEDURE USP_LISTAR_MUNICIPIO
AS
BEGIN
  SELECT  m.CODIGO_MUNICIPIO AS MUNICIPIO, m.NOMBRE_MUNICIPIO, m.ESTADO, r.CODIGO_REGION AS REGION, r.NOMBRE_REGION FROM MUNICIPIO m INNER JOIN MUNICIPIO_REGION mr ON m.CODIGO_MUNICIPIO = mr.CODIGO_MUNICIPIO INNER JOIN REGION r ON r.CODIGO_REGION = mr.CODIGO_REGION
END
-- USP_LISTAR_MUNICIPIO 
GO

CREATE PROCEDURE USP_LISTAR_MUNICIPIO_ID
@codigo int
AS
BEGIN
  SELECT * FROM MUNICIPIO WHERE CODIGO_MUNICIPIO = @codigo
END
-- USP_LISTAR_MUNICIPIO_ID 
GO

CREATE PROCEDURE USP_LISTAR_REGION_ID
@codigo int 
AS
BEGIN
  SELECT * FROM REGION WHERE CODIGO_REGION = @codigo
END
-- USP_LISTAR_REGION_ID 
GO


